Repository mastercomfig/team-comtress-2, pull requests merged in 2020-09, with the labels that each got.

#103 Clamp sv_maxunlag ConVar
  game/server/player_lagcompensation.cpp
Labels: tf2 issue

#123 add CoC
  CODE_OF_CONDUCT.md
Labels: documentation, rfc

#68 prevent invisible characters from being used in player names
  engine/baseclient.cpp
  game/shared/tf/tf_gamerules.cpp
  public/tier1/strtools.h
  tier1/strtools.cpp
Labels: enhancement

#110 Auto-collect money falling into func_respawnroom
  game/server/tf/entity_currencypack.cpp
Labels: enhancement

#193 Re-added colour clear to CRefractionView::Setup. Was removed as an op…
  game/client/viewrender.cpp
Labels: tc2 issue

#141 VRAD: Fix thread-sharing bug
  bitmap/float_bm4.cpp
  raytrace/raytrace.cpp
Labels: tf2

#194 Update community templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/tc2_bug_report.md
  .github/ISSUE_TEMPLATE/tf2_bug_report.md
  .github/PULL_REQUEST_TEMPLATE/docs_pr.md
  .github/PULL_REQUEST_TEMPLATE/feature_pr.md
  .github/PULL_REQUEST_TEMPLATE/tc2_bug_pr.md
  .github/PULL_REQUEST_TEMPLATE/tf2_bug_pr.md
Labels: documentation, rfc

#232 Fix typo in issue templates
  .github/ISSUE_TEMPLATE/tc2_bug_report.md
  .github/ISSUE_TEMPLATE/tf2_bug_report.md
Labels: documentation

#221 backport hud changes from upstream
  game_clean/copy/tf/custom/tc2/resource/ui/huddemomanpipes.res
Labels: enhancement, tc2

#155 Prevent sv_alltalk 1 exposing cloaked spies who are talking
  game/client/tf/vgui/tf_overview.cpp
Labels: bug, tf2

#154 Update README to better describe the project
  README.md
Labels: documentation, rfc

#234 Revert sv_restrict_aspect_ratio_fov back to 1
  engine/sv_main.cpp
Labels: rfc, tc2, wontfix

#302 Basic Installation Instrucions Improvements: warning about custom/tc2 and instructions to disable steam sync
  README.md
Labels: documentation

#309 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, tc2

#321 add "start" and "exit" so that cmd closes
  game_clean/hl2.bat
Labels: enhancement, tc2

#311 .bat: Don't pause on CI
  creategameprojects.bat
  creategameprojects_debug.bat
  creategameprojects_dev.bat
  download_libs.bat
Labels: tc2

#235 Re-enable special robot headshot/backstab animations
  game/shared/tf/tf_player_shared.cpp
Labels: enhancement, mvm, tf2

#214 Make tf_infinite_ammo non-STAGING_ONLY
  game/server/tf/tf_player.cpp
Labels: enhancement, tf2

#156 Prevent Loose Cannon pushing enemies around during truces on Hallowee…
  game/shared/tf/tf_weapon_grenade_pipebomb.cpp
Labels: tf2

#353 Switch to C++17 in Linux base Makefile
  devtools/makefile_base_posix.mak
Labels: tc2
