Repository mastercomfig/team-comtress-2, pull requests merged in 2020-10, with the labels that each got.

#391 Unlock various CS only cvars
  game/shared/movevars_shared.cpp
Labels: enhancement, tf2

#381 fix gunslinger combo hitreg
  game/shared/tf/tf_weapon_wrench.cpp
Labels: bug, help wanted, tf2

#380 remove flamethrower lag compensation
  game/shared/tf/tf_weapon_flamethrower.cpp
  game/shared/tf/tf_weaponbase.cpp
Labels: tf2

#363 Rework CTFPlayer::CanAirDash (double jumps)
  game/shared/tf/tf_player_shared.cpp
Labels: enhancement, tf2

#299 fix various airblast projectile bugs
  game/client/tf/hud_basedeathnotice.h
  game/client/tf/tf_hud_deathnotice.cpp
  game/server/tf/tf_projectile_arrow.cpp
  game/server/tf/tf_projectile_flare.cpp
  game/shared/tf/tf_gamerules.cpp
  game/shared/tf/tf_weapon_bat.cpp
  game/shared/tf/tf_weapon_bat.h
  game/shared/tf/tf_weapon_jar.cpp
Labels: bug, tf2

#281 Restricted minimum value of sv_client_max_interp_ratio to 2, as per issue #29
  engine/sv_main.cpp
Labels: enhancement, tf2

#366 Fix slope bug w/ surf maps
  game/shared/gamemovement.cpp
  game/shared/tf/tf_gamemovement.cpp
Labels: bug, help wanted, tf2
